services:
  sqoop:
    build: .
    container_name: sqoop
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - YARN_CONF_yarn_resourcemanager_hostname=resourcemanager
      - MAPRED_CONF_mapreduce_framework_name=yarn
    networks: [bigdata-net]
networks:
  bigdata-net:
    external: true
