services:
  hue:
    image: gethue/hue:4.10.0
    container_name: hue
    ports: ["8889:8888"]
    volumes:
      - ./hue-overrides.ini:/usr/share/hue/desktop/conf/z-custom.ini
    depends_on: [namenode, resourcemanager, hive-server, pig]
    networks: [bigdata-net]
networks:
  bigdata-net:
    external: true
